# name: Deploy

# on:
#  workflow_dispatch:

# jobs:
#  build:
#   runs-on: self-hosted
#   steps:
#    - uses: actions/checkout@v3
#    - name: Use Node
#      uses: actions/setup-node@v4
#      with:
#       node-version: "16"
#    - run: |
#       cd /home/dev/OtakuConnect
#       git pull
#       npm install
#       npm run build
#       npm install pm2
#       pm2 start src/socket.js

name: Run Application and Lint

on:
  push:
    branches-ignore:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Install dependencies
        run: pnpm install

      - name: Build Frontend
        run: pnpm run build

      - name: Start Backend
        run: pnpm run backend

      - name: Wait for Backend to Start
        run: sleep 10s

      - name: Check Backend Status
        run: curl http://localhost:your-backend-port
        continue-on-error: true

      - name: Stop Workflow if Backend is Not Running
        run: exit 1
        if: ${{ failure() }}

  lint:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Install dependencies
        run: pnpm install

      - name: Run ESLint
        run: pnpm run lint
