name: Deploy

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: '16'
      - run: |
          cd /home/dev/OtakuConnect
          git pull
          npm install
          npm run build
          npm install pm2 
          pm2 start src/socket.js

