name: Run Application and Lint

on:
  push:
    branches-ignore:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Install dependencies
        run: pnpm install

      - name: Build Frontend
        run: pnpm run build

      - name: Start Backend
        run: pnpm run backend

      - name: Wait for Backend to Start
        run: sleep 10s

      - name: Check Backend Status
        run: curl http://localhost:3001
        continue-on-error: true

      - name: Stop Workflow if Backend is Not Running
        run: exit 1
        if: ${{ failure() }}

  lint:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Install dependencies
        run: pnpm install

      - name: Run ESLint
        run: pnpm run lint
